/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LendingPool } from "./LendingPool";
export type { MockRWAToken } from "./MockRWAToken";
export type { RWAOracle } from "./RWAOracle";
